### PR TITLE
relationship inclusion improvements

### PR DESCRIPTION
**Pull request by nandorstanko**
In some cases we include the same entity multiple times. Depending from the inclusion order, sometimes the included entity is not the "real one", with the desired relationships/links. We have to check every instance of that single entity, and get the relationships from all of them, basically we need the most amount of data what we can get from the instances of that same included entity.

### CODE REVIEW

**Comment by pmarien** [comment]
@nandorstanko can you provide a test for this feature?

**Comment by pmarien** [comment]
@nandorstanko can you provide an example for your case? none of our 15 projects using this library has those problems until now. with an example I can perhaps understand it and put the fix in the new version

**Comment by nandorstanko** [comment]
@pmarien We have added an annotation to our entities, this way we can include relationships by default, and not only through request params. Example:
car -> manufacturer (include by default), parts
manufacturer -> address (don't include by default)
parts -> manufacturer

We want to list cars, including parts with their manufacturer AND manufacturer addresses (same brands for cars and parts), so we add this to request params include=parts.manufacturer.address. The default inclusion adds the manufacturer, but without the address. The request inclusion adds the manufacturer with the address, but now in the included array there are 2 items, same manufacturer, one with the included address, and one without. If the loop gets the one without the address first, then the address is not included afterwards.

I know that this is a very specific situation, because you don't use the default inclusion, so normally this never happens. My patch fixes our problem, and I think that it doesn't break your use cases, so I thought that we can add this. If it is a problem, then I will keep using my fork of this repo.

Thanks for your amazing work!

**Comment by pmarien** [comment]
@nandorstanko can not merge this feature because master is at version 3.x which looks very different.
But i have added a "merge" method in https://github.com/eosnewmedia/JSON-API-Common at version 3.1.0 and changed it here in version 3.1.0 to use it instead of "included()->set".
This should fix your problem if i understood it right.

**Pull request closed without merging**
